#!/usr/bin/env python3
"""Provisions a local Weave for the live Krater<->Weave e2e check, and writes the fixtures
`tests/live/test_weave_live.py` (and a manually-run Krater in live mode) need.

See `docs/dev/weave-e2e.md` for the full workflow. In short:

    uv run python scripts/dev/weave_e2e_setup.py
    # then, in the Weave checkout: bin/rails server -p 3000
    # then, in this checkout:      KRATER_WEAVE_MODE=live ... uv run uvicorn ...
    # then:                        uv run pytest -m live

This script only touches Weave through `bin/rails runner` (never its database directly) and only
touches Krater by writing the two fixture files below -- both gitignored, both regenerated (with fresh
secrets) on every run.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PROVISION_SCRIPT = Path(__file__).resolve().parent / "weave_e2e_provision.rb"

#: Where the raw provisioning result (client id/secret, user subs) is written.
#: Read by tests/live/test_weave_live.py. Never commit this -- it's a live credential.
FIXTURE_PATH = REPO_ROOT / ".weave_e2e_fixture.json"

#: A ready-to-source env file with the KRATER_* settings that point Krater at that fixture.
ENV_PATH = REPO_ROOT / ".env.weave-e2e"

DEFAULT_KRATER_REDIRECT_URI = "http://localhost:8201/auth/callback"


def run_provisioning(weave_dir: Path, *, redirect_uri: str, ruby_path: str | None) -> dict:
    env = dict(os.environ)
    if ruby_path:
        env["PATH"] = f"{ruby_path}:{env.get('PATH', '')}"
    env.setdefault("DATABASE_URL", "postgres://root:root@localhost")
    env["RAILS_ENV"] = env.get("RAILS_ENV", "development")
    env["KRATER_REDIRECT_URI"] = redirect_uri

    result = subprocess.run(
        ["bundle", "exec", "rails", "runner", str(PROVISION_SCRIPT)],
        cwd=weave_dir,
        env=env,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(f"weave_e2e_provision.rb failed (exit {result.returncode}) -- see stderr above")
    print(result.stderr, file=sys.stderr)  # the ruby script's own log lines

    try:
        # The ruby script prints exactly one JSON object; if anything else leaked onto
        # stdout (a gem warning, a stray puts), the JSON is still the last line.
        return json.loads(result.stdout.strip().splitlines()[-1])
    except (json.JSONDecodeError, IndexError) as exc:
        raise SystemExit(f"could not parse provisioning output as JSON:\n{result.stdout}") from exc


def write_fixtures(data: dict, *, krater_base_url: str) -> None:
    FIXTURE_PATH.write_text(json.dumps(data, indent=2) + "\n")

    env_lines = [
        "# Generated by scripts/dev/weave_e2e_setup.py -- do not commit, regenerated on every run.",
        "KRATER_ENV=development",
        f"KRATER_BASE_URL={krater_base_url}",
        "KRATER_WEAVE_MODE=live",
        f"KRATER_WEAVE_ISSUER={data['issuer']}",
        f"KRATER_WEAVE_CLIENT_ID={data['oauth_client_id']}",
        f"KRATER_WEAVE_CLIENT_SECRET={data['oauth_client_secret']}",
        "",
    ]
    ENV_PATH.write_text("\n".join(env_lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--weave-dir",
        default=os.environ.get("WEAVE_REPO_DIR", str(REPO_ROOT.parent / "weave")),
        help="Path to a Weave checkout with its dev database migrated (default: %(default)s, or $WEAVE_REPO_DIR)",
    )
    parser.add_argument(
        "--krater-base-url",
        default=os.environ.get("KRATER_BASE_URL", "http://localhost:8201"),
        help="Where Krater will run (default: %(default)s)",
    )
    parser.add_argument(
        "--ruby-shims",
        default=os.environ.get("RBENV_SHIMS_DIR", "/opt/rbenv/shims"),
        help="Prepended to PATH so `bundle`/`rails` resolve via rbenv (default: %(default)s)",
    )
    args = parser.parse_args()

    weave_dir = Path(args.weave_dir).resolve()
    if not (weave_dir / "bin" / "rails").exists():
        raise SystemExit(f"{weave_dir} doesn't look like a Weave checkout (no bin/rails)")

    redirect_uri = f"{args.krater_base_url.rstrip('/')}/auth/callback"
    data = run_provisioning(weave_dir, redirect_uri=redirect_uri, ruby_path=args.ruby_shims)
    write_fixtures(data, krater_base_url=args.krater_base_url)

    print(f"\nWrote {FIXTURE_PATH} and {ENV_PATH}.")
    print("Users provisioned (all share Weave's dev magic-link/password sign-in):")
    for role, user in data["users"].items():
        print(f"  {role:10s} {user['email']}  ({user['sub']})")
    print("\nNext steps -- see docs/dev/weave-e2e.md:")
    print(f"  1. In {weave_dir}: bin/rails server -p 3000 -b 0.0.0.0")
    print(f"  2. In {REPO_ROOT}: set -a; source .env.weave-e2e; set +a; uv run alembic upgrade head && \\")
    print("       uv run uvicorn krater.web.app:create_app --factory --port 8201")
    print("  3. uv run pytest -m live")


if __name__ == "__main__":
    main()
